[package]
name = "arc-guard"
description = "Guard around Arc<Mutex<T>> allowing you to write less boilerplate code."
version = "0.2.0"
license = "MIT"
authors = ["kunicmarko20 <kunicmarko20@gmail.com>"]
edition = "2018"
repository = "https://github.com/rustysoft/arc-guard"
